import { AgentBadge } from '@/app/components/AgentBadge';
import { Card, EmptyHint, PageShell, type TabDef } from '@/app/components/PageShell';
import { StreamingProgress } from '@/app/components/StreamingProgress';
import { CourseEntryCard } from '@/app/features/course/components/CourseEntryCard';
import { LearningPathDAG } from '@/app/features/course/components/LearningPathDAG';
import { ResourceTabs } from '@/app/features/course/components/ResourceTabs';
import { mockAssessment } from '@/app/features/course/mockData';

const tabs: TabDef[] = [
  {
    key: 'entry',
    label: '课程入口',
    description: 'Build persona and start the A3 course learning workflow.',
    render: () => <CourseEntryCard />,
  },
  {
    key: 'path',
    label: '学习路径',
    description: 'Knowledge graph order and personalized milestones.',
    render: () => <LearningPathDAG />,
  },
  {
    key: 'workbench',
    label: '资源工作台',
    description: 'Six resource types generated by existing 9-agent skills.',
    render: () => <ResourceTabs />,
  },
  {
    key: 'tutor',
    label: '辅导对话',
    description: 'P1 endpoint placeholder; route_tutor_question is intentionally not implemented in this P0 pass.',
    render: () => <EmptyHint text="TODO: P1 TutorDialog will reuse chat SSE and route questions to existing agents." />,
  },
  {
    key: 'assess',
    label: '效果评估',
    description: 'Assessment skeleton for the learning feedback loop.',
    render: () => (
      <Card title="Assessment preview" subtitle="P0 static skeleton">
        <div className="grid gap-4 md:grid-cols-[220px_1fr]">
          <div className="rounded-lg bg-slate-50 p-4 text-center">
            <div className="text-4xl font-semibold text-[#003399]">{mockAssessment.score}</div>
            <div className="mt-1 text-sm text-slate-500">mock score</div>
          </div>
          <div className="space-y-2">
            {mockAssessment.feedback.map((item) => (
              <p key={item} className="rounded-md border border-slate-100 p-2 text-sm text-slate-600">
                {item}
              </p>
            ))}
          </div>
        </div>
      </Card>
    ),
  },
];

export function CourseStudy() {
  return (
    <PageShell
      title="课程学习"
      subtitle="A3 multi-agent personalized learning workspace."
      tabs={tabs}
      defaultTab="entry"
      actions={
        <div className="flex items-center gap-2">
          <AgentBadge agentId="career_planner" />
          <AgentBadge agentId="doc_archivist" />
          <AgentBadge agentId="outcome_evaluator" />
        </div>
      }
    />
  );
}

export function CourseStudyProgressPreview() {
  return <StreamingProgress percentage={35} label="Course workflow" />;
}
