import type {
  AccountSecurity,
  AssetVersion,
  CapabilityScore,
  ComplianceSettings,
  NotificationSetting,
  ProfileAsset,
  ProfileWorkspace,
  SubmitChecklist,
  SubmitChecklistItem,
  UserProfile,
} from './types';

export const PROFILE_STORAGE_KEY = 'profile-workspace-demo';

const nowIso = () => new Date().toISOString();

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

const addDays = (days: number) =>
  new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();

function versions(prefix: string, title: string): AssetVersion[] {
  return [
    {
      id: `${prefix}-v3`,
      version: 'v3',
      title: `${title} v3`,
      updatedAt: hoursAgo(4),
      changelog: '补充评审意见、引用证据和提交格式校验。',
      sizeText: '2.4 MB',
    },
    {
      id: `${prefix}-v2`,
      version: 'v2',
      title: `${title} v2`,
      updatedAt: hoursAgo(36),
      changelog: '调整章节结构，合并导师反馈。',
      sizeText: '2.1 MB',
    },
    {
      id: `${prefix}-v1`,
      version: 'v1',
      title: `${title} v1`,
      updatedAt: hoursAgo(96),
      changelog: '初稿生成并完成基础校对。',
      sizeText: '1.7 MB',
    },
  ];
}

const defaultUser: UserProfile = {
  id: 'user-current',
  displayName: '陈同学',
  avatarText: '陈',
  email: 'chen_stu@example.edu.cn',
  school: '北京邮电大学',
  college: '网络空间安全学院',
  major: '网络空间安全',
  grade: '本科大三',
  enrollmentYear: 2023,
  identity: '学生',
  bio: '关注 AI 安全、零信任和高校数据安全治理，正在准备挑战杯和头部安全厂商实习。',
  goals: '保研 + 头部安全厂商实习 + 挑战杯作品完善',
  weeklyHours: '每周 20-25h',
  targetDirections: ['AI 安全', '零信任', '工业互联网安全'],
  tags: ['AI 安全', '零信任', '工业互联网', '挑战杯', '保研', '红队', '论文写作', '开源', '数据合规'],
  updatedAt: nowIso(),
};

const defaultCapabilities: CapabilityScore[] = [
  { id: 'cap-research', name: '科研能力', score: 68, category: 'research', evidence: '收藏 3 篇 AI 安全论文并生成综述提纲。', trend: 'up' },
  { id: 'cap-engineering', name: '工程能力', score: 74, category: 'engineering', evidence: '完成 zero-trust-gateway 原型和 OP-TEE 实验记录。', trend: 'up' },
  { id: 'cap-practice', name: '实战能力', score: 62, category: 'practice', evidence: '参与 CTF 题解沉淀和护网志愿服务。', trend: 'flat' },
  { id: 'cap-writing', name: '写作能力', score: 80, category: 'writing', evidence: '计划书与岗位分析报告持续迭代。', trend: 'up' },
  { id: 'cap-presentation', name: '表达能力', score: 70, category: 'presentation', evidence: '答辩 PPT 大纲已进入二轮修改。', trend: 'flat' },
  { id: 'cap-career', name: '职业规划', score: 72, category: 'career', evidence: '完成安全运营岗位能力差距分析。', trend: 'up' },
];

const assets: ProfileAsset[] = [
  {
    id: 'asset-challenge-proposal',
    title: '挑战杯计划书 v3',
    type: 'document',
    format: 'Doc',
    sourceModule: '选题写作',
    sourcePath: '/writing?tab=editor',
    summary: '面向工业互联网零信任安全治理的挑战杯计划书，包含背景、方案、创新点和落地路径。',
    contentPreview: '项目聚焦工业互联网远程运维中的身份可信、设备可信和访问控制问题，提出轻量级零信任网关方案。',
    tags: ['挑战杯', '零信任', '计划书'],
    version: 'v3',
    versions: versions('challenge-proposal', '挑战杯计划书'),
    status: 'reviewing',
    favorited: true,
    archived: false,
    createdAt: hoursAgo(180),
    updatedAt: hoursAgo(2),
    metadata: { wordCount: 12800, owner: '陈同学', citationCount: 18 },
  },
  {
    id: 'asset-zero-trust-review',
    title: '零信任方向综述',
    type: 'document',
    format: 'Markdown',
    sourceModule: '科研创新',
    sourcePath: '/research?tab=hot',
    summary: '梳理零信任架构、软件定义边界和工业互联网访问控制的代表论文。',
    contentPreview: '综述结构：研究背景、技术路线、典型系统、工业互联网适配、挑战与趋势。',
    tags: ['综述', '零信任', '论文'],
    version: 'v2',
    versions: versions('zero-trust-review', '零信任方向综述'),
    status: 'draft',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(240),
    updatedAt: hoursAgo(25),
    metadata: { wordCount: 7600, citationCount: 24 },
  },
  {
    id: 'asset-job-analysis',
    title: '岗位分析报告',
    type: 'document',
    format: 'PDF',
    sourceModule: '就业招聘',
    sourcePath: '/careers?tab=analysis',
    summary: '安全运营与云安全实习岗位的 JD 高频词、技能差距和简历改写建议。',
    contentPreview: '高频技能：日志分析、应急响应、SIEM、EDR、ATT&CK、Python 自动化。',
    tags: ['实习', '岗位分析', '安全运营'],
    version: 'v2',
    versions: versions('job-analysis', '岗位分析报告'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(168),
    updatedAt: hoursAgo(12),
    metadata: { wordCount: 5200, targetRole: '安全运营实习生' },
  },
  {
    id: 'asset-data-law-policy',
    title: '数据安全法政策解读',
    type: 'document',
    format: 'Markdown',
    sourceModule: '智能问答',
    sourcePath: '/chat?tab=policy',
    summary: '面向高校科研数据和学生个人信息场景的合规检查清单。',
    contentPreview: '重点关注数据分类分级、最小必要、脱敏处理、第三方系统接入和审计留痕。',
    tags: ['数据合规', '政策解读', '高校数据'],
    version: 'v1',
    versions: versions('data-law-policy', '数据安全法政策解读'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(110),
    updatedAt: hoursAgo(44),
    metadata: { wordCount: 4100, sourceCount: 6 },
  },
  {
    id: 'asset-crowdstrike-ethics',
    title: 'CrowdStrike 事件伦理分析报告',
    type: 'document',
    format: 'PDF',
    sourceModule: '智能问答',
    sourcePath: '/chat?tab=hot',
    summary: '从供应链风险、自动更新治理和安全厂商责任边界讨论典型事件。',
    contentPreview: '讨论重点：自动化更新的灰度策略、关键基础设施依赖、透明披露和客户补偿机制。',
    tags: ['安全伦理', '供应链', '热点研判'],
    version: 'v1',
    versions: versions('crowdstrike-ethics', 'CrowdStrike 事件伦理分析报告'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(220),
    updatedAt: hoursAgo(54),
    metadata: { wordCount: 4800, reviewStatus: '已校对' },
  },
  {
    id: 'asset-optee-report',
    title: 'OP-TEE 实验报告初稿',
    type: 'document',
    format: 'Doc',
    sourceModule: '科研创新',
    sourcePath: '/research?tab=lab',
    summary: '记录 QEMU 启动、TA 调用、日志采集和异常排查步骤。',
    contentPreview: '实验步骤：构建 qemu_v8，启动 secure world，加载 hello_world TA，记录 RPC 调用链。',
    tags: ['OP-TEE', '实验报告', '可信执行环境'],
    version: 'v1',
    versions: versions('optee-report', 'OP-TEE 实验报告初稿'),
    status: 'draft',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(130),
    updatedAt: hoursAgo(31),
    metadata: { wordCount: 3600, labEnvironment: 'QEMU v8' },
  },
  {
    id: 'asset-challenge-ppt',
    title: '挑战杯答辩 PPT v2',
    type: 'slides',
    format: 'PPT',
    sourceModule: '选题写作',
    sourcePath: '/writing?tab=ppt',
    summary: '包含问题背景、技术路线、创新点、实验验证和落地价值的 12 页大纲。',
    contentPreview: 'Slide 1 项目标题；Slide 2 痛点与场景；Slide 3 方案架构；Slide 4 核心算法；Slide 5 演示流程。',
    tags: ['挑战杯', '答辩', 'PPT'],
    version: 'v2',
    versions: versions('challenge-ppt', '挑战杯答辩 PPT'),
    status: 'reviewing',
    favorited: true,
    archived: false,
    createdAt: hoursAgo(150),
    updatedAt: hoursAgo(7),
    metadata: { slideCount: 12, scene: '国赛答辩' },
  },
  {
    id: 'asset-cisc-ppt',
    title: '信安赛汇报 PPT',
    type: 'slides',
    format: 'PPT',
    sourceModule: '实战进阶',
    sourcePath: '/practice?tab=contest',
    summary: '信安赛作品说明、演示流程和实验结果整理。',
    contentPreview: '汇报重点：系统架构、威胁模型、检测效果、部署截图、复盘改进。',
    tags: ['信安赛', '汇报', '竞赛'],
    version: 'v1',
    versions: versions('cisc-ppt', '信安赛汇报 PPT'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(260),
    updatedAt: hoursAgo(86),
    metadata: { slideCount: 18, scene: '省赛汇报' },
  },
  {
    id: 'asset-devsecops-ppt',
    title: '工程经济 DevSecOps 汇报',
    type: 'slides',
    format: 'PPT',
    sourceModule: '选题写作',
    sourcePath: '/writing?tab=ppt',
    summary: '课程汇报用 DevSecOps 安全投入与收益分析。',
    contentPreview: '内容包括安全左移、流水线门禁、漏洞修复成本和项目经济性评估。',
    tags: ['课程汇报', 'DevSecOps', '工程经济'],
    version: 'v1',
    versions: versions('devsecops-ppt', '工程经济 DevSecOps 汇报'),
    status: 'completed',
    favorited: false,
    archived: true,
    createdAt: hoursAgo(360),
    updatedAt: hoursAgo(160),
    metadata: { slideCount: 10, scene: '课程组会' },
  },
  {
    id: 'asset-weekly-ppt',
    title: '课程组会 PPT',
    type: 'slides',
    format: 'PPT',
    sourceModule: '计划任务',
    sourcePath: '/tasks?tab=timeline',
    summary: '本周实验进展、下周计划和风险点整理。',
    contentPreview: '本周完成：OP-TEE 环境搭建、挑战杯计划书修改、岗位报告补证据。',
    tags: ['组会', '周报', '任务'],
    version: 'v1',
    versions: versions('weekly-ppt', '课程组会 PPT'),
    status: 'draft',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(72),
    updatedAt: hoursAgo(16),
    metadata: { slideCount: 8, scene: '课程组会' },
  },
  {
    id: 'asset-zero-trust-gateway',
    title: 'zero-trust-gateway',
    type: 'code',
    format: 'Repo',
    sourceModule: '实战进阶',
    sourcePath: '/practice?tab=range',
    summary: 'Go 实现的轻量级零信任网关原型，支持设备身份、策略匹配和审计日志。',
    contentPreview: '核心模块：policy-engine、device-registry、audit-log、gateway-proxy。',
    tags: ['Go', '零信任', '网关'],
    version: 'v0.3',
    versions: versions('zero-trust-gateway', 'zero-trust-gateway'),
    status: 'draft',
    favorited: true,
    archived: false,
    createdAt: hoursAgo(420),
    updatedAt: hoursAgo(9),
    metadata: { language: 'Go', repo: 'https://example.com/zero-trust-gateway', contributions: '策略引擎与审计日志' },
  },
  {
    id: 'asset-llm-jailbreak-eval',
    title: 'llm-jailbreak-eval',
    type: 'code',
    format: 'Repo',
    sourceModule: '科研创新',
    sourcePath: '/research?tab=innovation',
    summary: 'LLM 越狱样本评测脚本，用于比较提示注入防护策略。',
    contentPreview: '包含样本集、评分脚本、模型输出解析和可视化报告生成。',
    tags: ['Python', 'AI 安全', '评测'],
    version: 'v0.2',
    versions: versions('llm-jailbreak-eval', 'llm-jailbreak-eval'),
    status: 'reviewing',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(320),
    updatedAt: hoursAgo(18),
    metadata: { language: 'Python', repo: 'https://example.com/llm-jailbreak-eval', contributions: '样本标注与评测脚本' },
  },
  {
    id: 'asset-ctf-writeups',
    title: 'ctf-writeups-2025',
    type: 'code',
    format: 'Repo',
    sourceModule: '交流论坛',
    sourcePath: '/forum?tab=exp',
    summary: 'CTF 题解与复盘模板，按 Web、Crypto、Pwn、Misc 分类沉淀。',
    contentPreview: '每篇题解包含环境、漏洞点、利用链、修复建议和复盘标签。',
    tags: ['CTF', 'Writeup', '复盘'],
    version: 'v1.0',
    versions: versions('ctf-writeups', 'ctf-writeups-2025'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(520),
    updatedAt: hoursAgo(65),
    metadata: { language: 'Markdown', repo: 'https://example.com/ctf-writeups-2025', contributions: 'Web 与 Misc 题解' },
  },
  {
    id: 'asset-optee-lab-notes',
    title: 'optee-qemu-lab-notes',
    type: 'code',
    format: 'Repo',
    sourceModule: '科研创新',
    sourcePath: '/research?tab=lab',
    summary: 'OP-TEE/QEMU 实验环境配置、日志采集脚本和问题记录。',
    contentPreview: '记录 buildroot、qemu 启动参数、TA 编译和串口日志采集脚本。',
    tags: ['OP-TEE', 'QEMU', 'TEE'],
    version: 'v0.1',
    versions: versions('optee-lab-notes', 'optee-qemu-lab-notes'),
    status: 'draft',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(210),
    updatedAt: hoursAgo(22),
    metadata: { language: 'Shell', repo: 'https://example.com/optee-qemu-lab-notes', contributions: '环境脚本与实验日志' },
  },
  {
    id: 'asset-snort-lab',
    title: 'snort-rule-lab',
    type: 'code',
    format: 'Repo',
    sourceModule: '实战进阶',
    sourcePath: '/practice?tab=tools',
    summary: 'Snort 规则实验，包含流量样本、规则编写和误报分析。',
    contentPreview: '实验场景：HTTP 异常请求、SQL 注入特征、基础告警和规则调优。',
    tags: ['Snort', '蓝队', '规则'],
    version: 'v0.1',
    versions: versions('snort-lab', 'snort-rule-lab'),
    status: 'completed',
    favorited: false,
    archived: true,
    createdAt: hoursAgo(480),
    updatedAt: hoursAgo(140),
    metadata: { language: 'Snort Rule', repo: 'https://example.com/snort-rule-lab', contributions: '规则编写与误报分析' },
  },
  {
    id: 'asset-cisc-certificate',
    title: '全国大学生信息安全竞赛省二等奖',
    type: 'proof',
    format: 'Certificate',
    sourceModule: '实战进阶',
    sourcePath: '/practice?tab=contest',
    summary: '全国大学生信息安全竞赛省赛获奖证书。',
    contentPreview: '证书用于竞赛经历、保研材料和简历附件归档。',
    tags: ['证书', '信安赛', '获奖'],
    version: 'scan-v1',
    versions: versions('cisc-certificate', '全国大学生信息安全竞赛省二等奖'),
    status: 'completed',
    favorited: true,
    archived: false,
    createdAt: hoursAgo(720),
    updatedAt: hoursAgo(200),
    metadata: { certificateNo: 'CISC-2025-BJ-0221', issuer: '赛事组委会', validUntil: '长期有效' },
  },
  {
    id: 'asset-challenge-certificate',
    title: '挑战杯校赛一等奖',
    type: 'proof',
    format: 'Certificate',
    sourceModule: '选题写作',
    sourcePath: '/writing?tab=proposal',
    summary: '挑战杯校赛一等奖证明，用于后续国赛材料包。',
    contentPreview: '证明材料包含获奖项目名称、团队成员、指导教师和学校盖章扫描件。',
    tags: ['挑战杯', '证书', '校赛'],
    version: 'scan-v1',
    versions: versions('challenge-certificate', '挑战杯校赛一等奖'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(620),
    updatedAt: hoursAgo(210),
    metadata: { certificateNo: 'BUPT-TB-2025-01', issuer: '北京邮电大学', validUntil: '长期有效' },
  },
  {
    id: 'asset-hvv-proof',
    title: '护网行动志愿者服务证明',
    type: 'proof',
    format: 'PDF',
    sourceModule: '实战进阶',
    sourcePath: '/practice?tab=hvv',
    summary: '护网行动服务时长与岗位职责证明。',
    contentPreview: '内容包括服务时间、蓝队值守职责、日志分析与应急响应参与记录。',
    tags: ['护网', '证明', '蓝队'],
    version: 'scan-v1',
    versions: versions('hvv-proof', '护网行动志愿者服务证明'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(560),
    updatedAt: hoursAgo(190),
    metadata: { issuer: '校级网安中心', validUntil: '长期有效', serviceHours: 56 },
  },
  {
    id: 'asset-mentor-letter',
    title: '导师推荐信扫描件',
    type: 'proof',
    format: 'PDF',
    sourceModule: '计划任务',
    sourcePath: '/tasks?tab=list',
    summary: '保研材料使用的导师推荐信扫描件。',
    contentPreview: '推荐信突出科研兴趣、工程实践、协作能力和竞赛投入。',
    tags: ['保研', '推荐信', '证明'],
    version: 'scan-v2',
    versions: versions('mentor-letter', '导师推荐信扫描件'),
    status: 'reviewing',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(260),
    updatedAt: hoursAgo(40),
    metadata: { issuer: '导师签字', validUntil: '2026-09-30' },
  },
  {
    id: 'asset-english-score',
    title: '英语成绩证明',
    type: 'proof',
    format: 'PDF',
    sourceModule: '计划任务',
    sourcePath: '/tasks?tab=list',
    summary: '四六级与英语课程成绩证明扫描件。',
    contentPreview: '用于保研材料、实习投递和校内奖项材料包。',
    tags: ['保研', '英语', '成绩'],
    version: 'scan-v1',
    versions: versions('english-score', '英语成绩证明'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(300),
    updatedAt: hoursAgo(76),
    metadata: { issuer: '教务系统', validUntil: '2026-12-31' },
  },
  {
    id: 'asset-transcript',
    title: '课程成绩单',
    type: 'proof',
    format: 'PDF',
    sourceModule: '计划任务',
    sourcePath: '/tasks?tab=list',
    summary: '课程成绩单与排名证明，用于保研材料包。',
    contentPreview: '包含专业核心课成绩、绩点排名和学院盖章。',
    tags: ['保研', '成绩单', '证明'],
    version: 'scan-v1',
    versions: versions('transcript', '课程成绩单'),
    status: 'completed',
    favorited: false,
    archived: false,
    createdAt: hoursAgo(360),
    updatedAt: hoursAgo(88),
    metadata: { issuer: '网络空间安全学院', validUntil: '2026-09-30' },
  },
];

function checklistItem(
  id: string,
  title: string,
  requirement: SubmitChecklistItem['requirement'],
  status: SubmitChecklistItem['status'],
  boundAssetId = '',
  note = '',
): SubmitChecklistItem {
  return {
    id,
    title,
    requirement,
    status,
    boundAssetId: boundAssetId || undefined,
    note,
  };
}

const submitChecklists: SubmitChecklist[] = [
  {
    id: 'checklist-challenge-final',
    name: '挑战杯国赛',
    scenario: '挑战杯',
    deadline: addDays(18),
    completionRate: 0,
    items: [
      checklistItem('challenge-application', '作品申报书（PDF）', '必交', 'ready', 'asset-challenge-proposal', '已绑定计划书 v3。'),
      checklistItem('challenge-report', '作品主体论文 / 报告', '必交', 'reviewing', 'asset-challenge-proposal', '需要补实验结果。'),
      checklistItem('challenge-appendix', '研究成果附录（代码/数据）', '建议', 'ready', 'asset-zero-trust-gateway'),
      checklistItem('challenge-ppt', '答辩 PPT', '必交', 'reviewing', 'asset-challenge-ppt'),
      checklistItem('challenge-teacher', '指导教师签字材料', '必交', 'missing', undefined, '等待线下签字扫描。'),
      checklistItem('challenge-duplicate', '查重报告', '必交', 'missing'),
    ],
    submitHistory: [],
  },
  {
    id: 'checklist-cisc',
    name: '信安赛作品提交',
    scenario: '信安赛',
    deadline: addDays(12),
    completionRate: 0,
    items: [
      checklistItem('cisc-manual', '作品说明书', '必交', 'reviewing', 'asset-cisc-ppt'),
      checklistItem('cisc-code', '代码仓库链接', '必交', 'ready', 'asset-zero-trust-gateway'),
      checklistItem('cisc-demo', '演示视频脚本', '建议', 'missing'),
      checklistItem('cisc-certificate', '参赛证明材料', '可选', 'ready', 'asset-cisc-certificate'),
    ],
    submitHistory: [],
  },
  {
    id: 'checklist-innovation-mid',
    name: '大创中期检查',
    scenario: '大创',
    deadline: addDays(26),
    completionRate: 0,
    items: [
      checklistItem('innovation-progress', '中期进展报告', '必交', 'reviewing', 'asset-optee-report'),
      checklistItem('innovation-finance', '经费使用说明', '必交', 'missing'),
      checklistItem('innovation-demo', '阶段成果截图', '建议', 'ready', 'asset-optee-lab-notes'),
    ],
    submitHistory: [],
  },
  {
    id: 'checklist-postgraduate',
    name: '保研材料包',
    scenario: '保研材料',
    deadline: addDays(43),
    completionRate: 0,
    items: [
      checklistItem('postgraduate-transcript', '课程成绩单', '必交', 'ready', 'asset-transcript'),
      checklistItem('postgraduate-english', '英语成绩证明', '必交', 'ready', 'asset-english-score'),
      checklistItem('postgraduate-letter', '导师推荐信', '建议', 'reviewing', 'asset-mentor-letter'),
      checklistItem('postgraduate-awards', '获奖证书合集', '建议', 'ready', 'asset-cisc-certificate'),
      checklistItem('postgraduate-personal', '个人陈述', '必交', 'missing'),
    ],
    submitHistory: [],
  },
  {
    id: 'checklist-internship',
    name: '实习投递材料',
    scenario: '实习投递',
    deadline: addDays(7),
    completionRate: 0,
    items: [
      checklistItem('intern-resume', '安全方向简历', '必交', 'missing'),
      checklistItem('intern-project', '项目经历说明', '建议', 'ready', 'asset-job-analysis'),
      checklistItem('intern-code', '代码仓库链接', '建议', 'ready', 'asset-llm-jailbreak-eval'),
      checklistItem('intern-certificate', '竞赛证明附件', '可选', 'ready', 'asset-challenge-certificate'),
    ],
    submitHistory: [],
  },
];

const notificationSettings: NotificationSetting[] = [
  { id: 'notice-contest-ddl', title: '竞赛截止提醒', description: '报名、初审、材料提交等关键日期提醒。', enabled: true, channel: '全部', advanceDays: 7, quietHoursEnabled: true },
  { id: 'notice-policy', title: '新政策发布通知', description: '网络安全、数据安全和高校治理政策更新。', enabled: true, channel: '站内', advanceDays: 1, quietHoursEnabled: false },
  { id: 'notice-research', title: '论文与基金机会推送', description: '匹配研究方向的论文、基金和开放实验室机会。', enabled: true, channel: '邮件', advanceDays: 3, quietHoursEnabled: true },
  { id: 'notice-forum', title: '论坛 @ 与回复', description: '社区互动、组队申请和资源交换消息。', enabled: true, channel: '站内', advanceDays: 0, quietHoursEnabled: false },
  { id: 'notice-weekly', title: '每周成长周报', description: '每周能力变化、资产沉淀和任务完成情况。', enabled: false, channel: '邮件', advanceDays: 0, quietHoursEnabled: true },
  { id: 'notice-task', title: '任务到期通知', description: '计划任务、里程碑和个人待办到期提醒。', enabled: true, channel: '浏览器', advanceDays: 2, quietHoursEnabled: true },
  { id: 'notice-asset', title: '资产更新提醒', description: '文档、PPT、代码和证明材料的版本变更。', enabled: false, channel: '站内', advanceDays: 0, quietHoursEnabled: false },
  { id: 'notice-account', title: '账户安全提醒', description: '新设备登录、数据导出和高风险操作提醒。', enabled: true, channel: '全部', advanceDays: 0, quietHoursEnabled: false },
];

const accountSecurity: AccountSecurity = {
  email: defaultUser.email,
  verified: true,
  membership: '教育版 · Pro',
  twoFactorEnabled: true,
  devices: [
    { id: 'device-laptop', name: 'Windows 笔记本', location: '北京', lastActiveAt: hoursAgo(1), trusted: true },
    { id: 'device-phone', name: 'iPhone 浏览器', location: '北京', lastActiveAt: hoursAgo(8), trusted: true },
    { id: 'device-lab', name: '实验室工作站', location: '北京', lastActiveAt: hoursAgo(32), trusted: false },
  ],
  sessions: [
    { id: 'session-current', deviceName: 'Windows 笔记本', ip: '10.12.8.24', location: '北京', lastActiveAt: hoursAgo(1), current: true, active: true },
    { id: 'session-phone', deviceName: 'iPhone 浏览器', ip: '10.12.8.51', location: '北京', lastActiveAt: hoursAgo(8), current: false, active: true },
    { id: 'session-lab', deviceName: '实验室工作站', ip: '172.16.2.18', location: '北京', lastActiveAt: hoursAgo(32), current: false, active: true },
  ],
  loginHistory: [
    { id: 'login-1', time: hoursAgo(1), location: '北京', device: 'Windows 笔记本', status: '成功' },
    { id: 'login-2', time: hoursAgo(8), location: '北京', device: 'iPhone 浏览器', status: '成功' },
    { id: 'login-3', time: hoursAgo(70), location: '未知', device: '陌生浏览器', status: '拦截' },
  ],
};

const complianceSettings: ComplianceSettings = {
  dataScope: '仅用于平台个性化推荐、学习路径规划和资产归档演示',
  aiContentNoticeAccepted: true,
  exportRequests: [],
  deletionRequested: false,
  authorizationRecords: [
    { id: 'auth-persona', scope: '画像生成', description: '使用写作、科研、任务和论坛行为生成用户画像。', updatedAt: hoursAgo(20), enabled: true },
    { id: 'auth-recommend', scope: '智能推荐', description: '使用兴趣标签和资产状态推荐行动。', updatedAt: hoursAgo(20), enabled: true },
    { id: 'auth-notice', scope: '提醒通知', description: '使用截止日期和任务状态触发提醒。', updatedAt: hoursAgo(20), enabled: true },
  ],
};

export function createDefaultProfileWorkspace(): ProfileWorkspace {
  const favoriteAssetIds = assets.filter((asset) => asset.favorited).map((asset) => asset.id);
  const archivedAssetIds = assets.filter((asset) => asset.archived).map((asset) => asset.id);
  const now = nowIso();

  return {
    id: 'profile-workspace-demo',
    user: { ...defaultUser, targetDirections: [...defaultUser.targetDirections], tags: [...defaultUser.tags], updatedAt: now },
    persona: {
      directionPreference: 'AI 安全 · 零信任 · 工业互联网安全',
      careerGoal: '头部安全厂商实习，优先安全平台研发或安全运营自动化方向。',
      researchGoal: '围绕 LLM Agent 安全评估、零信任访问控制和高校数据治理形成可发表综述或项目成果。',
      competitionGoal: '挑战杯作品完善、信安赛作品提交和 CTF 题解沉淀同步推进。',
      personaSources: [
        { id: 'source-writing', module: '选题写作', title: '挑战杯计划书与 PPT', description: '写作资产显示你正在围绕零信任场景持续迭代。', confidence: 92 },
        { id: 'source-research', module: '科研创新', title: 'AI 安全论文收藏', description: '科研模块中 AI 安全、隐私计算相关条目收藏较多。', confidence: 86 },
        { id: 'source-career', module: '就业招聘', title: '安全运营岗位分析', description: '岗位分析报告显示你关注安全运营和云安全实习。', confidence: 78 },
        { id: 'source-tasks', module: '计划任务', title: '竞赛和实验里程碑', description: '近期任务集中在挑战杯、OP-TEE 实验和保研材料。', confidence: 84 },
        { id: 'source-forum', module: '交流论坛', title: '论坛互动与题解沉淀', description: '互动内容偏向蓝队复盘、CTF 题解和工具实践。', confidence: 73 },
      ],
      weights: { writing: 24, research: 22, practice: 18, careers: 14, tasks: 14, forum: 8 },
      lastGeneratedAt: now,
      suggestion: '建议本周优先补齐挑战杯提交材料和零信任网关实验证据，再把岗位报告转入简历项目经历。',
    },
    capabilities: defaultCapabilities.map((item) => ({ ...item })),
    assets: assets.map((asset) => ({
      ...asset,
      tags: [...asset.tags],
      versions: asset.versions.map((version) => ({ ...version })),
      metadata: { ...asset.metadata },
    })),
    submitChecklists: submitChecklists.map((checklist) => ({
      ...checklist,
      items: checklist.items.map((item) => ({ ...item })),
      submitHistory: [],
    })),
    notificationSettings: notificationSettings.map((setting) => ({ ...setting })),
    accountSecurity: {
      ...accountSecurity,
      devices: accountSecurity.devices.map((device) => ({ ...device })),
      sessions: accountSecurity.sessions.map((session) => ({ ...session })),
      loginHistory: accountSecurity.loginHistory.map((item) => ({ ...item })),
    },
    complianceSettings: {
      ...complianceSettings,
      exportRequests: [],
      authorizationRecords: complianceSettings.authorizationRecords.map((item) => ({ ...item })),
    },
    favoriteAssetIds,
    archivedAssetIds,
    deletedAssetIds: [],
    selectedAssetId: undefined,
    selectedChecklistId: 'checklist-challenge-final',
    autosaveStatus: 'saved',
    savedAt: now,
    updatedAt: now,
  };
}
