import type {
  DataSourceStatus,
  DeadlineReminder,
  InsightItem,
  RecentAsset,
  RecommendedAction,
  WorkspaceDashboard,
  WorkspaceTask,
} from './types';

export const WORKSPACE_STORAGE_KEY = 'workspace-dashboard-demo';

const nowIso = () => new Date().toISOString();
const isoDate = (date: Date) => date.toISOString().slice(0, 10);
const addDays = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return isoDate(date);
};

function createTasks(): WorkspaceTask[] {
  const createdAt = nowIso();
  return [
    {
      id: 'task-challenge-cup-section',
      title: '完成挑战杯计划书 3.2 节初稿',
      description: '补齐技术路线、创新点与可行性分析，形成可供导师批注的 800 字初稿。',
      module: 'writing',
      targetPath: '/writing?tab=proposal',
      priority: 'high',
      estimateMinutes: 120,
      dueText: '今天 18:00 前',
      completed: false,
      sourceLabel: '计划书生成',
      evidenceIds: ['ev-policy-pipl', 'ev-paper-llm-phishing'],
      createdAt,
    },
    {
      id: 'task-career-citation',
      title: '核对网安就业岗位分析报告引用',
      description: '检查安全运营、云安全、AI 安全岗位引用来源，确认数据新鲜度和可追溯链接。',
      module: 'careers',
      targetPath: '/careers?tab=analysis',
      priority: 'medium',
      estimateMinutes: 35,
      dueText: '今天下午',
      completed: false,
      sourceLabel: '岗位分析',
      evidenceIds: ['ev-job-soc', 'ev-news-hvv'],
      createdAt,
    },
    {
      id: 'task-mentor-feedback',
      title: '回复导师关于实验方案的反馈',
      description: '围绕 OP-TEE/QEMU 实验环境、指标采集和对照组设置整理回复。',
      module: 'tasks',
      targetPath: '/tasks?tab=list',
      priority: 'medium',
      estimateMinutes: 20,
      dueText: '今天 21:00 前',
      completed: false,
      sourceLabel: '计划任务',
      evidenceIds: ['ev-optee-log'],
      createdAt,
    },
    {
      id: 'task-optee-log',
      title: '整理 OP-TEE/QEMU 实验日志',
      description: '把异常启动日志、可信应用调用链和复现实验步骤整理为报告附件。',
      module: 'research',
      targetPath: '/research?tab=lab',
      priority: 'high',
      estimateMinutes: 75,
      dueText: '明天上午',
      completed: false,
      sourceLabel: '开放实验室',
      evidenceIds: ['ev-optee-log'],
      createdAt,
    },
    {
      id: 'task-ai-security-paper',
      title: '生成 AI 安全论文精读摘要',
      description: '将收藏论文转为研究问题、方法、实验结果和可引用观点四段式摘要。',
      module: 'research',
      targetPath: '/research?tab=hot',
      priority: 'low',
      estimateMinutes: 45,
      dueText: '本周五',
      completed: true,
      sourceLabel: '热点文章',
      evidenceIds: ['ev-paper-agent-security'],
      createdAt,
    },
    {
      id: 'task-forum-team',
      title: '更新论坛组队需求',
      description: '补充项目分工、期望技能和本周同步时间，吸引后端与答辩同学加入。',
      module: 'forum',
      targetPath: '/forum?tab=team',
      priority: 'low',
      estimateMinutes: 25,
      dueText: '本周内',
      completed: false,
      sourceLabel: '项目组队',
      evidenceIds: ['ev-forum-team'],
      createdAt,
    },
  ];
}

function createDeadlines(): DeadlineReminder[] {
  return [
    {
      id: 'ddl-challenge-cup',
      title: '挑战杯课外学术作品提交',
      date: addDays(8),
      daysLeft: 8,
      module: 'writing',
      targetPath: '/writing?tab=proposal',
      urgency: 'high',
      status: 'active',
      description: '计划书正文、附件证明材料和答辩 PPT 大纲需要在校内系统提交前完成版本冻结。',
      actions: ['确认 3.2 节创新点', '补齐指导教师意见', '导出最终 PDF 与 PPT 大纲'],
      evidenceIds: ['ev-competition-cup', 'ev-policy-school'],
    },
    {
      id: 'ddl-cyber-innovation',
      title: '教育部网络安全创新创业大赛报名截止',
      date: addDays(3),
      daysLeft: 3,
      module: 'practice',
      targetPath: '/practice?tab=contest',
      urgency: 'critical',
      status: 'active',
      description: '队伍报名、作品简介和成员信息需完成确认，缺少作品亮点摘要。',
      actions: ['核对报名成员', '生成 300 字作品简介', '同步到团队看板'],
      evidenceIds: ['ev-competition-moe'],
    },
    {
      id: 'ddl-nsfc-youth',
      title: '国家自然科学基金青年项目初稿',
      date: addDays(21),
      daysLeft: 21,
      module: 'research',
      targetPath: '/research?tab=fund',
      urgency: 'medium',
      status: 'active',
      description: '基金方向可作为长期科研训练素材，当前需要形成研究背景和问题定义初稿。',
      actions: ['对比近三年资助方向', '生成研究问题候选', '沉淀到科研机会对比'],
      evidenceIds: ['ev-policy-nsfc'],
    },
    {
      id: 'ddl-security-review',
      title: '网安学术前沿综述投稿',
      date: addDays(35),
      daysLeft: 35,
      module: 'research',
      targetPath: '/research?tab=compare',
      urgency: 'low',
      status: 'active',
      description: '综述投稿窗口仍较宽裕，但文献结构和引用证据应尽早建立。',
      actions: ['整理近一年 AI 安全论文', '生成综述提纲', '加入文献精读计划'],
      evidenceIds: ['ev-paper-agent-security'],
    },
    {
      id: 'ddl-cisc-manual',
      title: '信安赛作品说明书提交',
      date: addDays(12),
      daysLeft: 12,
      module: 'writing',
      targetPath: '/writing?tab=editor',
      urgency: 'high',
      status: 'active',
      description: '作品说明书需要补充系统架构、创新点、测试结果和演示截图。',
      actions: ['补系统架构图说明', '引用实验日志', '生成评审版 Markdown'],
      evidenceIds: ['ev-optee-log', 'ev-competition-cisc'],
    },
    {
      id: 'ddl-internship-batch',
      title: '实习投递批次截止',
      date: addDays(6),
      daysLeft: 6,
      module: 'careers',
      targetPath: '/careers?tab=jobs',
      urgency: 'high',
      status: 'active',
      description: '安全运营和云安全方向实习本周集中截止，需要完成简历版本和投递清单。',
      actions: ['筛选目标岗位', '优化项目经历', '导出投递清单'],
      evidenceIds: ['ev-job-soc'],
    },
  ];
}

function createRecommendedActions(): RecommendedAction[] {
  return [
    {
      id: 'action-zero-trust-canvas',
      title: '完善“零信任在工业互联网的应用”创意画布',
      why: '系统检测到你已收藏 4 张零信任案例卡，但画布中的落地路径仍为空。',
      module: 'writing',
      targetPath: '/writing?tab=canvas',
      estimateMinutes: 35,
      priority: 'high',
      evidenceIds: ['ev-insight-zero-trust', 'ev-policy-cii'],
      status: 'active',
      expectedOutput: '一份可直接转入计划书的创意画布补全稿',
      aiPrompt: '帮我把零信任在工业互联网的应用整理成挑战杯创意画布。',
      benefit: '可补齐计划书创新点和应用场景，减少后续写作空转。',
      risk: '如果不先界定工业互联网场景，后续容易变成泛泛介绍。',
    },
    {
      id: 'action-hvv-career-report',
      title: '基于最新护网动态更新岗位分析报告',
      why: '护网动态数据源已更新，安全运营岗位的技能需求出现高频变化。',
      module: 'careers',
      targetPath: '/careers?tab=analysis',
      estimateMinutes: 25,
      priority: 'medium',
      evidenceIds: ['ev-news-hvv', 'ev-job-soc'],
      status: 'active',
      expectedOutput: '更新后的安全运营岗位能力画像',
      aiPrompt: '根据护网动态和岗位 JD，更新安全运营工程师岗位分析。',
      benefit: '能让简历项目经历更贴合近期招聘关键词。',
      risk: '招聘信息源仍为演示数据，需要后续接入真实招聘 API。',
    },
    {
      id: 'action-paper-to-citation',
      title: '将收藏论文转为计划书引用证据',
      why: '3 篇 AI 安全论文已收藏但未进入写作证据链。',
      module: 'writing',
      targetPath: '/writing?tab=cite',
      estimateMinutes: 30,
      priority: 'medium',
      evidenceIds: ['ev-paper-agent-security', 'ev-paper-llm-phishing'],
      status: 'active',
      expectedOutput: '7 条可插入计划书的引用证据',
      aiPrompt: '把收藏论文提炼成计划书引用证据并标注适合章节。',
      benefit: '提升计划书论证可信度，并减少手工整理引用的时间。',
      risk: '需要人工确认论文结论是否与当前方案严格对应。',
    },
    {
      id: 'action-sync-team-board',
      title: '同步本周任务到团队看板',
      why: '检测到 2 项计划任务状态变更未同步到团队看板。',
      module: 'tasks',
      targetPath: '/tasks?tab=board',
      estimateMinutes: 10,
      priority: 'low',
      evidenceIds: ['ev-forum-team'],
      status: 'active',
      expectedOutput: '团队看板中的本周交付项完成同步',
      aiPrompt: '将本周挑战杯、实验日志和岗位分析任务同步为团队看板条目。',
      benefit: '答辩演示时能展示从总览到计划任务的闭环。',
      risk: '当前为前端演示同步，不会写入真实协作系统。',
    },
    {
      id: 'action-policy-checklist',
      title: '使用智能问答生成政策合规检查清单',
      why: '你的项目涉及个人信息保护与数据安全，政策库中存在可引用条款。',
      module: 'chat',
      targetPath: '/chat?tab=policy',
      estimateMinutes: 20,
      priority: 'high',
      evidenceIds: ['ev-policy-pipl', 'ev-policy-data-security'],
      status: 'active',
      expectedOutput: '项目合规检查清单与答辩可用政策解读',
      aiPrompt: '请根据网络安全法、数据安全法和个人信息保护法生成项目合规检查清单。',
      benefit: '让项目方案能解释数据处理边界，适合答辩追问。',
      risk: '政策解读为演示辅助，需要最终人工审核。',
    },
    {
      id: 'action-forum-to-writing',
      title: '将论坛问答沉淀为写作素材',
      why: '论坛中有 2 条关于 OP-TEE 调试和数据集处理的高赞回答。',
      module: 'forum',
      targetPath: '/forum?tab=qa',
      estimateMinutes: 18,
      priority: 'low',
      evidenceIds: ['ev-forum-qa'],
      status: 'active',
      expectedOutput: '一组可插入实验报告的问答素材',
      aiPrompt: '把论坛问答整理成实验报告中的问题排查素材。',
      benefit: '把社区协作内容转成可复用写作材料。',
      risk: '问答内容需要去除个人信息和未经确认的结论。',
    },
  ];
}

function createRecentAssets(): RecentAsset[] {
  const now = new Date();
  const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 3600 * 1000).toISOString();
  return [
    {
      id: 'asset-llm-phishing-proposal',
      title: '基于 LLM 的钓鱼检测计划书',
      type: 'document',
      module: 'writing',
      targetPath: '/writing?tab=editor',
      summary: '围绕钓鱼邮件识别、提示注入防护和可解释风险评分形成的挑战杯计划书草稿。',
      contentPreview: '研究目标：构建面向高校邮箱场景的 LLM 辅助钓鱼检测流程，结合规则特征、语义判断和人工复核。',
      createdAt: hoursAgo(48),
      updatedAt: hoursAgo(2),
      status: 'draft',
      favorited: false,
    },
    {
      id: 'asset-challenge-ppt',
      title: '挑战杯答辩 PPT 大纲',
      type: 'ppt',
      module: 'writing',
      targetPath: '/writing?tab=ppt',
      summary: '包含问题背景、技术路线、创新点、实验验证和落地价值的 12 页大纲。',
      contentPreview: 'Slide 1 项目标题；Slide 2 痛点与场景；Slide 3 方案架构；Slide 4 核心算法；Slide 5 演示流程。',
      createdAt: hoursAgo(36),
      updatedAt: hoursAgo(7),
      status: 'reviewing',
      favorited: true,
    },
    {
      id: 'asset-soc-role-report',
      title: '岗位分析：安全运营工程师',
      type: 'report',
      module: 'careers',
      targetPath: '/careers?tab=analysis',
      summary: '对安全运营岗位的技能要求、实习 JD 高频词和项目经历匹配度进行分析。',
      contentPreview: '高频技能：日志分析、应急响应、SIEM、EDR、ATT&CK、Python 自动化。',
      createdAt: hoursAgo(54),
      updatedAt: hoursAgo(10),
      status: 'completed',
      favorited: false,
    },
    {
      id: 'asset-zero-trust-canvas',
      title: '工业互联网零信任创意画布',
      type: 'canvas',
      module: 'writing',
      targetPath: '/writing?tab=canvas',
      summary: '描述零信任在工业控制网络中的身份、设备、访问策略和审计闭环。',
      contentPreview: '用户群体：能源企业安全团队；核心价值：降低横向移动风险；关键能力：设备身份、细粒度授权。',
      createdAt: hoursAgo(72),
      updatedAt: hoursAgo(18),
      status: 'draft',
      favorited: false,
    },
    {
      id: 'asset-crowdstrike-ethics',
      title: 'CrowdStrike 事件伦理分析报告',
      type: 'report',
      module: 'chat',
      targetPath: '/chat?tab=hot',
      summary: '从供应链风险、自动更新治理和安全厂商责任边界讨论典型事件。',
      contentPreview: '讨论重点：自动化更新的灰度策略、关键基础设施依赖、透明披露和客户补偿机制。',
      createdAt: hoursAgo(96),
      updatedAt: hoursAgo(27),
      status: 'completed',
      favorited: false,
    },
    {
      id: 'asset-optee-report',
      title: 'OP-TEE 实验报告初稿',
      type: 'note',
      module: 'research',
      targetPath: '/research?tab=lab',
      summary: '记录 QEMU 启动、TA 调用、日志采集和异常排查步骤。',
      contentPreview: '实验步骤：构建 qemu_v8，启动 secure world，加载 hello_world TA，记录 RPC 调用链。',
      createdAt: hoursAgo(120),
      updatedAt: hoursAgo(31),
      status: 'draft',
      favorited: false,
    },
  ];
}

function createDataSources(): DataSourceStatus[] {
  return [
    {
      id: 'source-policy',
      name: '国家政策库',
      category: 'policy',
      freshnessScore: 96,
      lastSyncText: '今日 06:00 同步',
      status: 'fresh',
      affectedCards: ['国家政策', '政策合规检查清单', '计划书引用证据'],
      sourceCount: 128,
      description: '收录网络安全、数据安全、个人信息保护和高校数据治理相关政策条目。',
      suggestion: '保持每日同步，政策解读生成前优先检查该数据源。',
    },
    {
      id: 'source-competition',
      name: '竞赛与 DDL',
      category: 'competition',
      freshnessScore: 92,
      lastSyncText: '4 小时前',
      status: 'fresh',
      affectedCards: ['截止提醒', '今日要务', '实践竞赛专区'],
      sourceCount: 46,
      description: '聚合挑战杯、信安赛、创新创业大赛等竞赛时间和提交要求。',
      suggestion: '报名窗口期建议每天刷新一次，避免提交时间变更。',
    },
    {
      id: 'source-job',
      name: '招聘数据',
      category: 'job',
      freshnessScore: 82,
      lastSyncText: '昨日 22:00',
      status: 'warning',
      affectedCards: ['岗位分析', '实习投递批次截止', '简历优化'],
      sourceCount: 312,
      description: '模拟聚合安全运营、云安全、AI 安全和数据安全岗位 JD。',
      suggestion: '刷新后再生成简历关键词，当前岗位热词可能落后半天。',
    },
    {
      id: 'source-paper',
      name: '学术文献',
      category: 'paper',
      freshnessScore: 74,
      lastSyncText: '2 天前',
      status: 'outdated',
      affectedCards: ['科研热点文章', '论文精读摘要', '计划书引用证据'],
      sourceCount: 89,
      description: '维护 AI 安全、可信执行环境和供应链安全相关论文摘要。',
      suggestion: '建议先刷新再生成论文精读或综述提纲。',
    },
    {
      id: 'source-hvv',
      name: '护网动态',
      category: 'news',
      freshnessScore: 88,
      lastSyncText: '6 小时前',
      status: 'fresh',
      affectedCards: ['行业热点', '岗位分析', '智能问答热点研判'],
      sourceCount: 67,
      description: '模拟记录护网行动、威胁情报和安全运营场景变化。',
      suggestion: '推荐与就业岗位分析一起刷新，形成更贴近近期需求的技能画像。',
    },
    {
      id: 'source-forum',
      name: '论坛热度',
      category: 'forum',
      freshnessScore: 90,
      lastSyncText: '30 分钟前',
      status: 'fresh',
      affectedCards: ['交流论坛', '论坛问答素材', '组队需求'],
      sourceCount: 154,
      description: '维护站内问答、组队帖、资源交换和经验帖热度。',
      suggestion: '状态健康，可直接用于生成社区素材摘要。',
    },
    {
      id: 'source-assets',
      name: '项目资产库',
      category: 'system',
      freshnessScore: 84,
      lastSyncText: '8 小时前',
      status: 'warning',
      affectedCards: ['最近生成物', '个人资产库', '写作素材'],
      sourceCount: 28,
      description: '记录当前演示用户的文档、PPT、报告、画布和笔记资产。',
      suggestion: '导出或收藏资产后会自动进入保存队列。',
    },
    {
      id: 'source-chat-cache',
      name: '智能问答缓存',
      category: 'system',
      freshnessScore: 61,
      lastSyncText: '上次同步失败',
      status: 'failed',
      affectedCards: ['智能问答', '推荐行动', '政策解读'],
      sourceCount: 17,
      errorMessage: '演示缓存索引过期，最近一次同步未完成。',
      description: '模拟保存智能问答的主题、政策、热点和写作辅助缓存。',
      suggestion: '可手动刷新；失败时不影响总览展示，但会提示数据源风险。',
    },
  ];
}

function createInsights(): InsightItem[] {
  return [
    {
      id: 'insight-agent-security',
      type: 'industry',
      title: 'AI Agent 安全框架成为新热点',
      summary: '多家安全团队开始关注 Agent 工具调用边界、提示注入、权限隔离和审计追踪。',
      tags: ['AI 安全', '市场趋势'],
      source: '演示行业观察',
      sourceUrl: 'https://example.com/agent-security',
      heatScore: 96,
      reliability: 86,
      publishedAt: addDays(-1),
      favorited: false,
      relatedModules: ['research', 'chat', 'writing'],
      suggestedActions: ['加入热点研判', '提炼为计划书研究背景', '生成合规检查清单'],
    },
    {
      id: 'insight-zero-trust-energy',
      type: 'industry',
      title: '零信任在能源行业落地案例增多',
      summary: '能源企业更关注设备身份、远程运维授权和横向移动防护，适合作为工业互联网选题场景。',
      tags: ['零信任', '工控安全'],
      source: '演示产业案例库',
      sourceUrl: 'https://example.com/zero-trust-energy',
      heatScore: 88,
      reliability: 82,
      publishedAt: addDays(-2),
      favorited: true,
      relatedModules: ['writing', 'research'],
      suggestedActions: ['引用到创意画布', '加入挑战杯场景描述', '创建计划任务'],
    },
    {
      id: 'insight-supply-chain-cicd',
      type: 'industry',
      title: '供应链攻击针对 CI/CD 环境激增',
      summary: '攻击者更频繁利用构建脚本、依赖污染和凭据泄露进入交付链路。',
      tags: ['供应链', '云安全'],
      source: '演示威胁情报',
      sourceUrl: 'https://example.com/supply-chain-cicd',
      heatScore: 91,
      reliability: 79,
      publishedAt: addDays(-3),
      favorited: false,
      relatedModules: ['practice', 'chat'],
      suggestedActions: ['加入问答分析', '整理成靶场练习主题', '沉淀为论坛讨论'],
    },
    {
      id: 'insight-cloud-runtime',
      type: 'industry',
      title: '云原生运行时防护需求提升',
      summary: '容器逃逸、Kubernetes 权限和运行时行为监测成为企业安全建设重点。',
      tags: ['云安全', '市场趋势'],
      source: '演示市场观察',
      sourceUrl: 'https://example.com/cloud-runtime',
      heatScore: 84,
      reliability: 80,
      publishedAt: addDays(-4),
      favorited: false,
      relatedModules: ['careers', 'research'],
      suggestedActions: ['更新岗位分析', '加入学习路径', '生成论文精读列表'],
    },
    {
      id: 'insight-data-privacy-computing',
      type: 'industry',
      title: '数据安全与隐私计算融合趋势明显',
      summary: '数据要素流通推动隐私计算、访问控制和审计追踪协同落地。',
      tags: ['AI 安全', '市场趋势'],
      source: '演示数据安全周报',
      sourceUrl: 'https://example.com/privacy-computing',
      heatScore: 81,
      reliability: 84,
      publishedAt: addDays(-5),
      favorited: false,
      relatedModules: ['writing', 'chat'],
      suggestedActions: ['生成政策合规检查', '引用到写作', '加入问答分析'],
    },
    {
      id: 'social-data-leak',
      type: 'social',
      title: '多地政务平台数据泄露事件调查进展',
      summary: '公众对政务数据最小化采集、访问审计和外包服务安全责任关注升高。',
      tags: ['数据泄露', '社会治理', '个人信息保护'],
      source: '演示社会热点',
      sourceUrl: 'https://example.com/gov-data-leak',
      heatScore: 94,
      reliability: 78,
      publishedAt: addDays(-1),
      favorited: false,
      relatedModules: ['chat', 'writing'],
      suggestedActions: ['生成舆情分析', '引用到政策背景', '加入任务跟踪'],
    },
    {
      id: 'social-ai-fraud',
      type: 'social',
      title: 'AI 诈骗典型案例引发关注',
      summary: '深度伪造语音、换脸视频和自动化话术正在改变反诈教育与取证方式。',
      tags: ['AI 诈骗', '社会治理'],
      source: '演示案例库',
      sourceUrl: 'https://example.com/ai-fraud',
      heatScore: 92,
      reliability: 81,
      publishedAt: addDays(-2),
      favorited: false,
      relatedModules: ['practice', 'chat'],
      suggestedActions: ['加入问答分析', '生成安全教育素材', '沉淀为论坛话题'],
    },
    {
      id: 'social-competition-growth',
      type: 'social',
      title: '大学生网络安全竞赛参与规模提升',
      summary: '高校课程、企业命题和实战平台联动增强，竞赛成果更容易转化为项目经历。',
      tags: ['高校赛事'],
      source: '演示教育观察',
      sourceUrl: 'https://example.com/campus-contest',
      heatScore: 79,
      reliability: 83,
      publishedAt: addDays(-3),
      favorited: true,
      relatedModules: ['practice', 'forum'],
      suggestedActions: ['加入计划任务', '更新组队需求', '引用到项目背景'],
    },
    {
      id: 'social-pipl-governance',
      type: 'social',
      title: '个人信息保护专项治理持续推进',
      summary: '应用过度索权、儿童信息保护和第三方 SDK 合规仍是重点关注方向。',
      tags: ['个人信息保护', '社会治理'],
      source: '演示合规观察',
      sourceUrl: 'https://example.com/pipl-governance',
      heatScore: 87,
      reliability: 86,
      publishedAt: addDays(-4),
      favorited: false,
      relatedModules: ['chat', 'writing'],
      suggestedActions: ['生成政策解读', '加入合规检查清单', '引用到写作'],
    },
    {
      id: 'social-research-data',
      type: 'social',
      title: '高校科研数据合规问题受到关注',
      summary: '科研数据采集、脱敏、共享和长期保存的管理边界成为高校治理议题。',
      tags: ['高校赛事', '个人信息保护'],
      source: '演示高校治理简报',
      sourceUrl: 'https://example.com/research-data',
      heatScore: 76,
      reliability: 82,
      publishedAt: addDays(-6),
      favorited: false,
      relatedModules: ['research', 'chat'],
      suggestedActions: ['加入科研计划', '生成数据管理清单', '引用到政策章节'],
    },
  ];
}

function createPolicies(): InsightItem[] {
  return [
    {
      id: 'policy-cybersecurity-law',
      type: 'policy',
      title: '网络安全法',
      summary: '明确网络运行安全、关键信息基础设施保护、个人信息保护和网络安全监督管理要求。',
      tags: ['网络安全', '基础法律'],
      source: '全国人大公开法律文本（演示条目）',
      sourceUrl: 'https://example.com/cybersecurity-law',
      heatScore: 90,
      reliability: 96,
      publishedAt: '2017-06-01',
      favorited: false,
      relatedModules: ['chat', 'writing'],
      suggestedActions: ['生成政策解读', '引用到计划书背景', '加入合规任务'],
    },
    {
      id: 'policy-data-security-law',
      type: 'policy',
      title: '数据安全法',
      summary: '围绕数据分类分级、风险监测、应急处置和数据处理活动安全责任建立制度框架。',
      tags: ['数据安全', '分类分级'],
      source: '全国人大公开法律文本（演示条目）',
      sourceUrl: 'https://example.com/data-security-law',
      heatScore: 86,
      reliability: 96,
      publishedAt: '2021-09-01',
      favorited: false,
      relatedModules: ['chat', 'writing'],
      suggestedActions: ['生成项目数据分类清单', '引用到合规章节', '加入问答分析'],
    },
    {
      id: 'policy-pipl',
      type: 'policy',
      title: '个人信息保护法',
      summary: '规范个人信息处理规则、敏感个人信息保护、个人权利和处理者义务。',
      tags: ['个人信息保护', '合规检查'],
      source: '全国人大公开法律文本（演示条目）',
      sourceUrl: 'https://example.com/pipl',
      heatScore: 88,
      reliability: 97,
      publishedAt: '2021-11-01',
      favorited: true,
      relatedModules: ['chat', 'writing'],
      suggestedActions: ['生成合规检查清单', '引用到计划书', '加入任务'],
    },
    {
      id: 'policy-cii',
      type: 'policy',
      title: '关键信息基础设施安全保护条例',
      summary: '对关键信息基础设施认定、运营者责任、安全保护措施和监督管理提出要求。',
      tags: ['关键信息基础设施', '零信任'],
      source: '国务院公开政策文本（演示条目）',
      sourceUrl: 'https://example.com/cii-regulation',
      heatScore: 84,
      reliability: 95,
      publishedAt: '2021-09-01',
      favorited: false,
      relatedModules: ['writing', 'research'],
      suggestedActions: ['引用到工业互联网场景', '生成政策解读', '加入任务'],
    },
    {
      id: 'policy-talent-whitepaper',
      type: 'policy',
      title: '网络安全人才实战能力白皮书',
      summary: '强调攻防实践、工程化能力、合规意识和跨学科协作能力培养。',
      tags: ['人才培养', '实战能力'],
      source: '演示白皮书摘要',
      sourceUrl: 'https://example.com/security-talent-whitepaper',
      heatScore: 73,
      reliability: 82,
      publishedAt: addDays(-16),
      favorited: false,
      relatedModules: ['careers', 'practice'],
      suggestedActions: ['更新职业路径', '加入学习计划', '引用到竞赛背景'],
    },
    {
      id: 'policy-campus-data',
      type: 'policy',
      title: '高校数据安全管理相关政策',
      summary: '关注高校科研数据、学生个人信息、系统权限和第三方服务接入治理。',
      tags: ['高校数据', '数据安全'],
      source: '演示高校治理资料',
      sourceUrl: 'https://example.com/campus-data-policy',
      heatScore: 78,
      reliability: 84,
      publishedAt: addDays(-30),
      favorited: false,
      relatedModules: ['research', 'chat'],
      suggestedActions: ['生成高校场景检查表', '引用到研究背景', '加入问答分析'],
    },
  ];
}

export function createDefaultDashboard(): WorkspaceDashboard {
  const tasks = createTasks();
  const deadlines = createDeadlines();
  const recommendedActions = createRecommendedActions();
  const recentAssets = createRecentAssets();
  const insights = createInsights();
  const policies = createPolicies();
  const completedTaskIds = tasks.filter((task) => task.completed).map((task) => task.id);
  const favoriteAssetIds = recentAssets.filter((asset) => asset.favorited).map((asset) => asset.id);
  const favoriteInsightIds = insights.filter((insight) => insight.favorited).map((insight) => insight.id);
  const favoritePolicyIds = policies.filter((policy) => policy.favorited).map((policy) => policy.id);
  const today = isoDate(new Date());

  return {
    id: 'workspace-demo',
    userName: '陈同学',
    today,
    dailyBrief: {
      id: 'brief-today',
      date: today,
      summary: '今天建议先处理挑战杯计划书和教育部网安创新创业大赛报名，再补齐岗位分析引用与 OP-TEE 实验日志。',
      keyTasks: ['完成挑战杯计划书 3.2 节初稿', '整理 OP-TEE/QEMU 实验日志', '回复导师实验方案反馈'],
      urgentDeadlines: ['教育部网络安全创新创业大赛报名截止', '实习投递批次截止'],
      recommendedActions: ['生成政策合规检查清单', '完善工业互联网零信任创意画布'],
      risks: ['学术文献数据源已过期，论文精读前建议刷新', '智能问答缓存同步失败，热点研判可能不完整'],
      dataWarnings: ['学术文献 2 天未同步', '智能问答缓存上次同步失败'],
    },
    tasks,
    deadlines,
    recommendedActions,
    recentAssets,
    dataSources: createDataSources(),
    insights,
    policies,
    completedTaskIds,
    ignoredDeadlineIds: [],
    handledDeadlineIds: [],
    dismissedActionIds: [],
    postponedActionIds: [],
    favoriteAssetIds,
    favoriteInsightIds,
    favoritePolicyIds,
    pinnedItemIds: [],
    autosaveStatus: 'saved',
    savedAt: nowIso(),
    updatedAt: nowIso(),
  };
}
